### ISSUE TITLE
Unable to cancel an open order 

### ISSUE THREAD

**Issue by ivanaszuber** [CounterpartyXCP/counterwallet#734]
Canceling an open order gives the error:

```
failoverAPI: Call failed (failed over across all servers). Method: broadcast_tx; Last error: JSON-RPC Error:
Type: Server error

Code: -32000

Message: Bad status code returned: '500'. result body: '{"result":null,"error":{"code":-26,"message":"64: scriptpubkey"},"id":0} '.
```

After that the Cancel button is disabled and the order still open (visible in the Market and in Open orders)

**Comment by pryds** [comment]
For what it's worth, it seems that information about the disabled button is only stored client-side, suggesting that the order is still genuinely open. If I log in via another browser, I can click the cancel button again (and get the same error message again).

**Comment by ouziel-slama** [comment]
@ivanaszuber: I can not reproduce. Is it happens every time or only sometimes? is it you did another transaction just before the cancel ? seems to me an error in transactions chaining in the production server (seems list unspent return spent outputs).

Meantime, I just push a commit to re-enable the `cancel` button if the transaction failed: a priori, wait some minutes and retry the cancel should works.

**Comment by pryds** [comment]
For me, it happened every time I tried. I even tried again after approximately a day's time, so there shouldn't be any other recent transactions. In the meantime, the order has expired, so I don't know if it's still a problem.

**Comment by ivanaszuber** [comment]
@ouziel-slama I just created a new order and tried to cancel it and got the same error. So yes, for me it happens every time. The old order is still there with the Cancel button disabled (didn't try a different browser since I got the error on the second order)

**Comment by ivanaszuber** [comment]
btw, same error appears when trying to issue a new asset (see https://github.com/CounterpartyXCP/counterwallet/issues/730), issue more of the same asset or lock an asset

**Comment by ouziel-slama** [comment]
OK, this bug should be resolved here: https://github.com/CounterpartyXCP/counterparty-lib/commit/8e3590ee5295cc646793ba8bbbd28bcb79ddb43a

**Comment by JopHartog** [comment]
I still have the same error when I try to cancel an order using the Counterwallet.io wallet.

failoverAPI: Call failed (failed over across all servers). Method: broadcast_tx; Last error: JSON-RPC Error:
Type: Server error

Code: -32000

Message: Bad status code returned: '500'. result body: '{"result":null,"error":{"code":-26,"message":"64: scriptpubkey"},"id":0} '.

Am I forgetting something ?

**Comment by btcdrak** [comment]
@JopHartog Changes are not rolled out the the counterwallet servers immediately. Usually you have to wait until the next server updates if you arent running your own nodes.

**Comment by JopHartog** [comment]
@btcdrak Thank you for  the clarification, I will try it on my own node.

**Comment by btcdrak** [comment]
@JopHartog At risk of stating the obvious, remember it's in the develop branch not master.

**Comment by adamkrellenstein** [comment]
Solved with https://github.com/CounterpartyXCP/counterparty-lib/commit/8e3590ee5295cc646793ba8bbbd28bcb79ddb43a

**Comment by unsystemizer** [comment]
Users still having issues - https://counterpartytalk.org/t/cannot-cancel-order/1114
Do we need more info?
Should we reopen this?

**Comment by ivanaszuber** [comment]
I just tested this and it seems to be working fine. I was able to cancel an open order without issues

**Comment by JopHartog** [comment]
The issue was solved. Was trying it on a not updated node.



Best Regards, / Met vriendelijke groet,

Jop Hartog

Phone: +31 (0)628947224
E-mail: info@jophartog.nl
Web: www.JopHartog.nl <http://www.jophartog.nl>
PGP:                0x32E40321
